name: 🚀 Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the desired feature and it's use-case.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Suggest how to implement the addition or change. Please include prototype/workaround/sketch/reference implementation.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context
      description: Any alternative solutions or features you considered, a more detailed explanation, stack traces, related issues, links for context, etc.
    validations:
      required: false

  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might introduce a breaking change
          required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment details (OS name and version, etc.)
      description: You can use `v doctor` to fill up this section.
    validations:
      required: true
