name: Docs

on:
  push:
    paths-ignore: ['**.yml', '!.github/workflows/docs.yml']
  pull_request:
    paths-ignore: ['**.yml', '!.github/workflows/docs.yml']
  workflow_dispatch:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.sha || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup V
        uses: vlang/setup-v@v1.4
      - name: Setup Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libcurl4-openssl-dev
          version: 1.0
      - name: Check markdown
        run: v check-md -hide-warnings ~/.vmodules/vibe

  deploy:
    if: github.event_name == 'push' && github.ref_name == 'main' && github.repository == 'ttytm/vibe'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref_name != 'main' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Setup V
        uses: vlang/setup-v@v1.4
      - name: Build docs
        run: docs/build.vsh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/site'
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
