name: Lint Docs

on:
  push:
    paths: ['**/*.md', '**/*.yml']
  pull_request:

env:
  WORK_PATH: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/
  MOD_PATH: ~/.vmodules/vibe/

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.WORK_PATH }}vlang/
          key: vlang-nightly

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Setup libcurl
        run: sudo apt update && sudo apt install libcurl4-openssl-dev

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3

      - name: Copy ${{ github.event.repository.name }} to .vmodules
        run: cp -r ${{ env.WORK_PATH }} ${{ env.MOD_PATH }}

      - name: Check Markdown
        run: v check-md -hide-warnings ${{ env.MOD_PATH }}
