name: Lint Docs

on:
  push:
    paths: ['**/*.md', '**/*.yml']
  pull_request:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  MOD_PATH: ~/.vmodules/vibe/

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: vlang
          key: ${{ runner.os }}-v-

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Setup libcurl
        run: sudo apt update && sudo apt install libcurl4-openssl-dev

      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}

      - name: Copy ${{ env.REPO_NAME }} to .vmodules
        run: cp -r ${{ env.REPO_NAME }} ${{ env.MOD_PATH }}

      - name: Check Markdown
        run: v check-md -hide-warnings ${{ env.MOD_PATH }}
