name: Lint

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ubuntu-latest-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v version
      - name: Verify formatting
        run: v fmt -verify ~/.vmodules/vibe && exit 0 || v fmt -diff . && exit 1
      - name: Vet
        run: v vet -W ~/.vmodules/vibe
