name: CI

on:
  workflow_call:

jobs:
  setup:
    strategy:
      matrix:
        include:
          - os: macos-latest
            v_archive: v_macos_arm64.zip
          - os: macos-12
            v_archive: v_macos_x86_64.zip
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup V
        run: |
          curl -LO https://github.com/vlang/v/releases/latest/download/${{ matrix.v_archive }}
          unzip -o ${{ matrix.v_archive }}
          mv v ~/v
          ~/v/v symlink && v -showcc self && v doctor
      - uses: actions/checkout@v4
        with:
          path: vibe
      - name: Setup V module
        run: |
          mv vibe ~/.vmodules/vibe
          ~/.vmodules/vibe/curl/build.vsh --silent
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ matrix.os }}-${{ github.sha }}

  test:
    needs: setup
    strategy:
      matrix:
        os: [macos-12, macos-latest]
        cc: [tcc, clang]
        optimization: ['', '-W -cstrict']
        exclude:
          - cc: tcc
            optimization: '-W -cstrict'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      VFLAGS: -cg -stats -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ matrix.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink
      - name: Run tests
        run: v ${{ env.VFLAGS }} test ~/.vmodules/vibe
